[package]
name = "suxquads"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "suxquads-load"
path = "src/bin/load.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
oxrdfio.workspace = true
oxrdf.workspace = true
rayon.workspace = true

[lints]
workspace = true
